USE [testORM]
GO

/****** Object:  Table [dbo].[BS_Person]    Script Date: 2017/5/16 14:40:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BS_Person](
	[Id_NR] [int] NOT NULL,
	[Name_TX] [nvarchar](150) NOT NULL,
	[Description_TX] [nvarchar](500) NULL,
 CONSTRAINT [PK_BS_Person] PRIMARY KEY CLUSTERED 
(
	[Id_NR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


