#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["TestK8s.WebApp/TestK8s.WebApp.csproj", "TestK8s.WebApp/"]
RUN dotnet restore "TestK8s.WebApp/TestK8s.WebApp.csproj"
COPY . .
WORKDIR "/src/TestK8s.WebApp"
RUN dotnet build "TestK8s.WebApp.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TestK8s.WebApp.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TestK8s.WebApp.dll"]