function Hd = matlabFir1
%MATLABFIR1 Returns a discrete-time filter object.

%
% M-File generated by MATLAB(R) 7.6 and the Signal Processing Toolbox 6.9.
%
% Generated on: 15-Jan-2010 09:43:55
%

% Butterworth Highpass filter designed using FDESIGN.HIGHPASS.

% All frequency values are in Hz.
Fs = 200;  % Sampling Frequency

N  = 6;   % Order
Fc = 10;  % Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.highpass('N,Fc', N, Fc, Fs);
Hd = design(h, 'butter');

% [EOF]
